using System;

namespace MetaphysicsIndustries.Giza
{
    public class Supergrammar : Grammar
    {
        public Definition def_0_grammar = new Definition("grammar");
        public Definition def_1_definition = new Definition("definition");
        public Definition def_2_defmod = new Definition("defmod");
        public Definition def_3_defmod_item = new Definition("defmod-item");
        public Definition def_4_id_whitespace = new Definition("id-whitespace");
        public Definition def_5_id_ignore = new Definition("id-ignore");
        public Definition def_6_id_case = new Definition("id-case");
        public Definition def_7_id_contiguous = new Definition("id-contiguous");
        public Definition def_8_expr = new Definition("expr");
        public Definition def_9_orexpr = new Definition("orexpr");
        public Definition def_10_subexpr = new Definition("subexpr");
        public Definition def_11_modifier = new Definition("modifier");
        public Definition def_12_number = new Definition("number");
        public Definition def_13_identifier = new Definition("identifier");
        public Definition def_14_literal = new Definition("literal");
        public Definition def_15_charclass = new Definition("charclass");
        public Definition def_16_unicodechar = new Definition("unicodechar");
        public Definition def_17_comment = new Definition("comment");

        public StartNode node_grammar_0_start;
        public DefRefNode node_grammar_1_definition;
        public DefRefNode node_grammar_2_comment;
        public EndNode node_grammar_3_end;
        public StartNode node_definition_0_start;
        public DefRefNode node_definition_1_defmod;
        public DefRefNode node_definition_2_identifier;
        public CharNode node_definition_3__003D_;
        public DefRefNode node_definition_4_expr;
        public CharNode node_definition_5__003B_;
        public EndNode node_definition_6_end;
        public StartNode node_defmod_0_start;
        public CharNode node_defmod_1__003C_;
        public DefRefNode node_defmod_2_defmod_002D_item;
        public CharNode node_defmod_3__002C_;
        public DefRefNode node_defmod_4_defmod_002D_item;
        public CharNode node_defmod_5__003E_;
        public EndNode node_defmod_6_end;
        public StartNode node_defmod_item_0_start;
        public DefRefNode node_defmod_item_1_id_002D_whitespace;
        public DefRefNode node_defmod_item_2_id_002D_ignore;
        public CharNode node_defmod_item_3__002D_;
        public DefRefNode node_defmod_item_4_id_002D_case;
        public DefRefNode node_defmod_item_5_id_002D_contiguous;
        public EndNode node_defmod_item_6_end;
        public StartNode node_id_whitespace_0_start;
        public CharNode node_id_whitespace_1_whitespace;
        public CharNode node_id_whitespace_2_whitespace;
        public CharNode node_id_whitespace_3_whitespace;
        public CharNode node_id_whitespace_4_whitespace;
        public CharNode node_id_whitespace_5_whitespace;
        public CharNode node_id_whitespace_6_whitespace;
        public CharNode node_id_whitespace_7_whitespace;
        public CharNode node_id_whitespace_8_whitespace;
        public CharNode node_id_whitespace_9_whitespace;
        public CharNode node_id_whitespace_10_whitespace;
        public EndNode node_id_whitespace_11_end;
        public StartNode node_id_ignore_0_start;
        public CharNode node_id_ignore_1_ignore;
        public CharNode node_id_ignore_2_ignore;
        public CharNode node_id_ignore_3_ignore;
        public CharNode node_id_ignore_4_ignore;
        public CharNode node_id_ignore_5_ignore;
        public CharNode node_id_ignore_6_ignore;
        public EndNode node_id_ignore_7_end;
        public StartNode node_id_case_0_start;
        public CharNode node_id_case_1_case;
        public CharNode node_id_case_2_case;
        public CharNode node_id_case_3_case;
        public CharNode node_id_case_4_case;
        public EndNode node_id_case_5_end;
        public StartNode node_id_contiguous_0_start;
        public CharNode node_id_contiguous_1_contiguous;
        public CharNode node_id_contiguous_2_contiguous;
        public CharNode node_id_contiguous_3_contiguous;
        public CharNode node_id_contiguous_4_contiguous;
        public CharNode node_id_contiguous_5_contiguous;
        public CharNode node_id_contiguous_6_contiguous;
        public CharNode node_id_contiguous_7_contiguous;
        public CharNode node_id_contiguous_8_contiguous;
        public CharNode node_id_contiguous_9_contiguous;
        public CharNode node_id_contiguous_10_contiguous;
        public EndNode node_id_contiguous_11_end;
        public StartNode node_expr_0_start;
        public DefRefNode node_expr_1_subexpr;
        public DefRefNode node_expr_2_orexpr;
        public DefRefNode node_expr_3_comment;
        public EndNode node_expr_4_end;
        public StartNode node_orexpr_0_start;
        public CharNode node_orexpr_1__0028_;
        public DefRefNode node_orexpr_2_expr;
        public CharNode node_orexpr_3__007C_;
        public DefRefNode node_orexpr_4_expr;
        public CharNode node_orexpr_5__0029_;
        public DefRefNode node_orexpr_6_modifier;
        public EndNode node_orexpr_7_end;
        public StartNode node_subexpr_0_start;
        public DefRefNode node_subexpr_1_identifier;
        public DefRefNode node_subexpr_2_literal;
        public DefRefNode node_subexpr_3_charclass;
        public DefRefNode node_subexpr_4_modifier;
        public CharNode node_subexpr_5__003A_;
        public DefRefNode node_subexpr_6_tag;
        public EndNode node_subexpr_7_end;
        public StartNode node_modifier_0_start;
        public CharNode node_modifier_1__002A__002B__003F_;
        public EndNode node_modifier_2_end;
        public StartNode node_number_0_start;
        public CharNode node_number_1__005C_d;
        public EndNode node_number_2_end;
        public StartNode node_identifier_0_start;
        public CharNode node_identifier_1__005C_l_002D__;
        public CharNode node_identifier_2__005C_l_005C_d_002D__;
        public EndNode node_identifier_3_end;
        public StartNode node_literal_0_start;
        public CharNode node_literal_1__0027_;
        public CharNode node_literal_2__005E__005C__005C__0027_;
        public CharNode node_literal_3__005C_;
        public CharNode node_literal_4_rnt_005C__005C__0027_;
        public DefRefNode node_literal_5_unicodechar;
        public CharNode node_literal_6__0027_;
        public EndNode node_literal_7_end;
        public StartNode node_charclass_0_start;
        public CharNode node_charclass_1__005B_;
        public CharNode node_charclass_2__005E__005C__005C__005C__005B__005C__005D_;
        public CharNode node_charclass_3__005C_;
        public CharNode node_charclass_4_wldsrnt_005C__005C__005C__005B__005C__005D_;
        public DefRefNode node_charclass_5_unicodechar;
        public CharNode node_charclass_6__005D_;
        public EndNode node_charclass_7_end;
        public StartNode node_unicodechar_0_start;
        public CharNode node_unicodechar_1__005C_x;
        public CharNode node_unicodechar_2__005C_x;
        public CharNode node_unicodechar_3__005C_dabcdef;
        public CharNode node_unicodechar_4__005C_dabcdef;
        public CharNode node_unicodechar_5__005C_dabcdef;
        public CharNode node_unicodechar_6__005C_dabcdef;
        public EndNode node_unicodechar_7_end;
        public StartNode node_comment_0_start;
        public CharNode node_comment_1__002F__002A_;
        public CharNode node_comment_2__002F__002A_;
        public CharNode node_comment_3__005E__002A_;
        public CharNode node_comment_4__002A_;
        public CharNode node_comment_5__005E__002A__002F_;
        public CharNode node_comment_6__002A_;
        public CharNode node_comment_7__002F_;
        public CharNode node_comment_8__002F__002F_;
        public CharNode node_comment_9__002F__002F_;
        public CharNode node_comment_10__005E__005C_r_005C_n;
        public CharNode node_comment_11__005C_r_005C_n;
        public EndNode node_comment_12_end;

        public Supergrammar()
        {
            Definitions.Add(def_0_grammar);
            Definitions.Add(def_1_definition);
            Definitions.Add(def_2_defmod);
            Definitions.Add(def_3_defmod_item);
            Definitions.Add(def_4_id_whitespace);
            Definitions.Add(def_5_id_ignore);
            Definitions.Add(def_6_id_case);
            Definitions.Add(def_7_id_contiguous);
            Definitions.Add(def_8_expr);
            Definitions.Add(def_9_orexpr);
            Definitions.Add(def_10_subexpr);
            Definitions.Add(def_11_modifier);
            Definitions.Add(def_12_number);
            Definitions.Add(def_13_identifier);
            Definitions.Add(def_14_literal);
            Definitions.Add(def_15_charclass);
            Definitions.Add(def_16_unicodechar);
            Definitions.Add(def_17_comment);

            def_0_grammar.IgnoreCase = false;
            def_0_grammar.IgnoreWhitespace = true;
            def_0_grammar.Contiguous = false;
            node_grammar_0_start = new StartNode();
            node_grammar_1_definition = new DefRefNode(def_1_definition, "definition");
            node_grammar_2_comment = new DefRefNode(def_17_comment, "comment");
            node_grammar_3_end = new EndNode();
            def_0_grammar.Nodes.Add(node_grammar_0_start);
            def_0_grammar.Nodes.Add(node_grammar_1_definition);
            def_0_grammar.Nodes.Add(node_grammar_2_comment);
            def_0_grammar.Nodes.Add(node_grammar_3_end);
            def_0_grammar.start = node_grammar_0_start;
            def_0_grammar.end = node_grammar_3_end;
            node_grammar_0_start.NextNodes.Add(node_grammar_1_definition);
            node_grammar_0_start.NextNodes.Add(node_grammar_2_comment);
            node_grammar_1_definition.NextNodes.Add(node_grammar_1_definition);
            node_grammar_1_definition.NextNodes.Add(node_grammar_2_comment);
            node_grammar_1_definition.NextNodes.Add(node_grammar_3_end);
            node_grammar_2_comment.NextNodes.Add(node_grammar_1_definition);
            node_grammar_2_comment.NextNodes.Add(node_grammar_2_comment);
            node_grammar_2_comment.NextNodes.Add(node_grammar_3_end);

            def_1_definition.IgnoreCase = false;
            def_1_definition.IgnoreWhitespace = true;
            def_1_definition.Contiguous = false;
            node_definition_0_start = new StartNode();
            node_definition_1_defmod = new DefRefNode(def_2_defmod, "defmod");
            node_definition_2_identifier = new DefRefNode(def_13_identifier, "identifier");
            node_definition_3__003D_ = new CharNode(CharClass.FromUndelimitedCharClassText("="), "=");
            node_definition_4_expr = new DefRefNode(def_8_expr, "expr");
            node_definition_5__003B_ = new CharNode(CharClass.FromUndelimitedCharClassText(";"), ";");
            node_definition_6_end = new EndNode();
            def_1_definition.Nodes.Add(node_definition_0_start);
            def_1_definition.Nodes.Add(node_definition_1_defmod);
            def_1_definition.Nodes.Add(node_definition_2_identifier);
            def_1_definition.Nodes.Add(node_definition_3__003D_);
            def_1_definition.Nodes.Add(node_definition_4_expr);
            def_1_definition.Nodes.Add(node_definition_5__003B_);
            def_1_definition.Nodes.Add(node_definition_6_end);
            def_1_definition.start = node_definition_0_start;
            def_1_definition.end = node_definition_6_end;
            node_definition_0_start.NextNodes.Add(node_definition_1_defmod);
            node_definition_0_start.NextNodes.Add(node_definition_2_identifier);
            node_definition_1_defmod.NextNodes.Add(node_definition_1_defmod);
            node_definition_1_defmod.NextNodes.Add(node_definition_2_identifier);
            node_definition_2_identifier.NextNodes.Add(node_definition_3__003D_);
            node_definition_3__003D_.NextNodes.Add(node_definition_4_expr);
            node_definition_4_expr.NextNodes.Add(node_definition_5__003B_);
            node_definition_5__003B_.NextNodes.Add(node_definition_6_end);

            def_2_defmod.IgnoreCase = false;
            def_2_defmod.IgnoreWhitespace = true;
            def_2_defmod.Contiguous = false;
            node_defmod_0_start = new StartNode();
            node_defmod_1__003C_ = new CharNode(CharClass.FromUndelimitedCharClassText("<"), "<");
            node_defmod_2_defmod_002D_item = new DefRefNode(def_3_defmod_item, "defmod-item");
            node_defmod_3__002C_ = new CharNode(CharClass.FromUndelimitedCharClassText(","), ",");
            node_defmod_4_defmod_002D_item = new DefRefNode(def_3_defmod_item, "defmod-item");
            node_defmod_5__003E_ = new CharNode(CharClass.FromUndelimitedCharClassText(">"), ">");
            node_defmod_6_end = new EndNode();
            def_2_defmod.Nodes.Add(node_defmod_0_start);
            def_2_defmod.Nodes.Add(node_defmod_1__003C_);
            def_2_defmod.Nodes.Add(node_defmod_2_defmod_002D_item);
            def_2_defmod.Nodes.Add(node_defmod_3__002C_);
            def_2_defmod.Nodes.Add(node_defmod_4_defmod_002D_item);
            def_2_defmod.Nodes.Add(node_defmod_5__003E_);
            def_2_defmod.Nodes.Add(node_defmod_6_end);
            def_2_defmod.start = node_defmod_0_start;
            def_2_defmod.end = node_defmod_6_end;
            node_defmod_0_start.NextNodes.Add(node_defmod_1__003C_);
            node_defmod_1__003C_.NextNodes.Add(node_defmod_2_defmod_002D_item);
            node_defmod_2_defmod_002D_item.NextNodes.Add(node_defmod_3__002C_);
            node_defmod_2_defmod_002D_item.NextNodes.Add(node_defmod_5__003E_);
            node_defmod_3__002C_.NextNodes.Add(node_defmod_4_defmod_002D_item);
            node_defmod_4_defmod_002D_item.NextNodes.Add(node_defmod_3__002C_);
            node_defmod_4_defmod_002D_item.NextNodes.Add(node_defmod_5__003E_);
            node_defmod_5__003E_.NextNodes.Add(node_defmod_6_end);

            def_3_defmod_item.IgnoreCase = false;
            def_3_defmod_item.IgnoreWhitespace = true;
            def_3_defmod_item.Contiguous = false;
            node_defmod_item_0_start = new StartNode();
            node_defmod_item_1_id_002D_whitespace = new DefRefNode(def_4_id_whitespace, "id-whitespace");
            node_defmod_item_2_id_002D_ignore = new DefRefNode(def_5_id_ignore, "id-ignore");
            node_defmod_item_3__002D_ = new CharNode(CharClass.FromUndelimitedCharClassText("-"), "-");
            node_defmod_item_4_id_002D_case = new DefRefNode(def_6_id_case, "id-case");
            node_defmod_item_5_id_002D_contiguous = new DefRefNode(def_7_id_contiguous, "id-contiguous");
            node_defmod_item_6_end = new EndNode();
            def_3_defmod_item.Nodes.Add(node_defmod_item_0_start);
            def_3_defmod_item.Nodes.Add(node_defmod_item_1_id_002D_whitespace);
            def_3_defmod_item.Nodes.Add(node_defmod_item_2_id_002D_ignore);
            def_3_defmod_item.Nodes.Add(node_defmod_item_3__002D_);
            def_3_defmod_item.Nodes.Add(node_defmod_item_4_id_002D_case);
            def_3_defmod_item.Nodes.Add(node_defmod_item_5_id_002D_contiguous);
            def_3_defmod_item.Nodes.Add(node_defmod_item_6_end);
            def_3_defmod_item.start = node_defmod_item_0_start;
            def_3_defmod_item.end = node_defmod_item_6_end;
            node_defmod_item_0_start.NextNodes.Add(node_defmod_item_1_id_002D_whitespace);
            node_defmod_item_0_start.NextNodes.Add(node_defmod_item_2_id_002D_ignore);
            node_defmod_item_0_start.NextNodes.Add(node_defmod_item_5_id_002D_contiguous);
            node_defmod_item_1_id_002D_whitespace.NextNodes.Add(node_defmod_item_6_end);
            node_defmod_item_2_id_002D_ignore.NextNodes.Add(node_defmod_item_3__002D_);
            node_defmod_item_2_id_002D_ignore.NextNodes.Add(node_defmod_item_4_id_002D_case);
            node_defmod_item_3__002D_.NextNodes.Add(node_defmod_item_4_id_002D_case);
            node_defmod_item_4_id_002D_case.NextNodes.Add(node_defmod_item_6_end);
            node_defmod_item_5_id_002D_contiguous.NextNodes.Add(node_defmod_item_6_end);

            def_4_id_whitespace.IgnoreCase = true;
            def_4_id_whitespace.IgnoreWhitespace = false;
            def_4_id_whitespace.Contiguous = false;
            node_id_whitespace_0_start = new StartNode();
            node_id_whitespace_1_whitespace = new CharNode(CharClass.FromUndelimitedCharClassText("w"), "whitespace");
            node_id_whitespace_2_whitespace = new CharNode(CharClass.FromUndelimitedCharClassText("h"), "whitespace");
            node_id_whitespace_3_whitespace = new CharNode(CharClass.FromUndelimitedCharClassText("i"), "whitespace");
            node_id_whitespace_4_whitespace = new CharNode(CharClass.FromUndelimitedCharClassText("t"), "whitespace");
            node_id_whitespace_5_whitespace = new CharNode(CharClass.FromUndelimitedCharClassText("e"), "whitespace");
            node_id_whitespace_6_whitespace = new CharNode(CharClass.FromUndelimitedCharClassText("s"), "whitespace");
            node_id_whitespace_7_whitespace = new CharNode(CharClass.FromUndelimitedCharClassText("p"), "whitespace");
            node_id_whitespace_8_whitespace = new CharNode(CharClass.FromUndelimitedCharClassText("a"), "whitespace");
            node_id_whitespace_9_whitespace = new CharNode(CharClass.FromUndelimitedCharClassText("c"), "whitespace");
            node_id_whitespace_10_whitespace = new CharNode(CharClass.FromUndelimitedCharClassText("e"), "whitespace");
            node_id_whitespace_11_end = new EndNode();
            def_4_id_whitespace.Nodes.Add(node_id_whitespace_0_start);
            def_4_id_whitespace.Nodes.Add(node_id_whitespace_1_whitespace);
            def_4_id_whitespace.Nodes.Add(node_id_whitespace_2_whitespace);
            def_4_id_whitespace.Nodes.Add(node_id_whitespace_3_whitespace);
            def_4_id_whitespace.Nodes.Add(node_id_whitespace_4_whitespace);
            def_4_id_whitespace.Nodes.Add(node_id_whitespace_5_whitespace);
            def_4_id_whitespace.Nodes.Add(node_id_whitespace_6_whitespace);
            def_4_id_whitespace.Nodes.Add(node_id_whitespace_7_whitespace);
            def_4_id_whitespace.Nodes.Add(node_id_whitespace_8_whitespace);
            def_4_id_whitespace.Nodes.Add(node_id_whitespace_9_whitespace);
            def_4_id_whitespace.Nodes.Add(node_id_whitespace_10_whitespace);
            def_4_id_whitespace.Nodes.Add(node_id_whitespace_11_end);
            def_4_id_whitespace.start = node_id_whitespace_0_start;
            def_4_id_whitespace.end = node_id_whitespace_11_end;
            node_id_whitespace_0_start.NextNodes.Add(node_id_whitespace_1_whitespace);
            node_id_whitespace_1_whitespace.NextNodes.Add(node_id_whitespace_2_whitespace);
            node_id_whitespace_2_whitespace.NextNodes.Add(node_id_whitespace_3_whitespace);
            node_id_whitespace_3_whitespace.NextNodes.Add(node_id_whitespace_4_whitespace);
            node_id_whitespace_4_whitespace.NextNodes.Add(node_id_whitespace_5_whitespace);
            node_id_whitespace_5_whitespace.NextNodes.Add(node_id_whitespace_6_whitespace);
            node_id_whitespace_6_whitespace.NextNodes.Add(node_id_whitespace_7_whitespace);
            node_id_whitespace_7_whitespace.NextNodes.Add(node_id_whitespace_8_whitespace);
            node_id_whitespace_8_whitespace.NextNodes.Add(node_id_whitespace_9_whitespace);
            node_id_whitespace_9_whitespace.NextNodes.Add(node_id_whitespace_10_whitespace);
            node_id_whitespace_10_whitespace.NextNodes.Add(node_id_whitespace_11_end);

            def_5_id_ignore.IgnoreCase = true;
            def_5_id_ignore.IgnoreWhitespace = false;
            def_5_id_ignore.Contiguous = false;
            node_id_ignore_0_start = new StartNode();
            node_id_ignore_1_ignore = new CharNode(CharClass.FromUndelimitedCharClassText("i"), "ignore");
            node_id_ignore_2_ignore = new CharNode(CharClass.FromUndelimitedCharClassText("g"), "ignore");
            node_id_ignore_3_ignore = new CharNode(CharClass.FromUndelimitedCharClassText("n"), "ignore");
            node_id_ignore_4_ignore = new CharNode(CharClass.FromUndelimitedCharClassText("o"), "ignore");
            node_id_ignore_5_ignore = new CharNode(CharClass.FromUndelimitedCharClassText("r"), "ignore");
            node_id_ignore_6_ignore = new CharNode(CharClass.FromUndelimitedCharClassText("e"), "ignore");
            node_id_ignore_7_end = new EndNode();
            def_5_id_ignore.Nodes.Add(node_id_ignore_0_start);
            def_5_id_ignore.Nodes.Add(node_id_ignore_1_ignore);
            def_5_id_ignore.Nodes.Add(node_id_ignore_2_ignore);
            def_5_id_ignore.Nodes.Add(node_id_ignore_3_ignore);
            def_5_id_ignore.Nodes.Add(node_id_ignore_4_ignore);
            def_5_id_ignore.Nodes.Add(node_id_ignore_5_ignore);
            def_5_id_ignore.Nodes.Add(node_id_ignore_6_ignore);
            def_5_id_ignore.Nodes.Add(node_id_ignore_7_end);
            def_5_id_ignore.start = node_id_ignore_0_start;
            def_5_id_ignore.end = node_id_ignore_7_end;
            node_id_ignore_0_start.NextNodes.Add(node_id_ignore_1_ignore);
            node_id_ignore_1_ignore.NextNodes.Add(node_id_ignore_2_ignore);
            node_id_ignore_2_ignore.NextNodes.Add(node_id_ignore_3_ignore);
            node_id_ignore_3_ignore.NextNodes.Add(node_id_ignore_4_ignore);
            node_id_ignore_4_ignore.NextNodes.Add(node_id_ignore_5_ignore);
            node_id_ignore_5_ignore.NextNodes.Add(node_id_ignore_6_ignore);
            node_id_ignore_6_ignore.NextNodes.Add(node_id_ignore_7_end);

            def_6_id_case.IgnoreCase = true;
            def_6_id_case.IgnoreWhitespace = false;
            def_6_id_case.Contiguous = false;
            node_id_case_0_start = new StartNode();
            node_id_case_1_case = new CharNode(CharClass.FromUndelimitedCharClassText("c"), "case");
            node_id_case_2_case = new CharNode(CharClass.FromUndelimitedCharClassText("a"), "case");
            node_id_case_3_case = new CharNode(CharClass.FromUndelimitedCharClassText("s"), "case");
            node_id_case_4_case = new CharNode(CharClass.FromUndelimitedCharClassText("e"), "case");
            node_id_case_5_end = new EndNode();
            def_6_id_case.Nodes.Add(node_id_case_0_start);
            def_6_id_case.Nodes.Add(node_id_case_1_case);
            def_6_id_case.Nodes.Add(node_id_case_2_case);
            def_6_id_case.Nodes.Add(node_id_case_3_case);
            def_6_id_case.Nodes.Add(node_id_case_4_case);
            def_6_id_case.Nodes.Add(node_id_case_5_end);
            def_6_id_case.start = node_id_case_0_start;
            def_6_id_case.end = node_id_case_5_end;
            node_id_case_0_start.NextNodes.Add(node_id_case_1_case);
            node_id_case_1_case.NextNodes.Add(node_id_case_2_case);
            node_id_case_2_case.NextNodes.Add(node_id_case_3_case);
            node_id_case_3_case.NextNodes.Add(node_id_case_4_case);
            node_id_case_4_case.NextNodes.Add(node_id_case_5_end);

            def_7_id_contiguous.IgnoreCase = true;
            def_7_id_contiguous.IgnoreWhitespace = false;
            def_7_id_contiguous.Contiguous = false;
            node_id_contiguous_0_start = new StartNode();
            node_id_contiguous_1_contiguous = new CharNode(CharClass.FromUndelimitedCharClassText("c"), "contiguous");
            node_id_contiguous_2_contiguous = new CharNode(CharClass.FromUndelimitedCharClassText("o"), "contiguous");
            node_id_contiguous_3_contiguous = new CharNode(CharClass.FromUndelimitedCharClassText("n"), "contiguous");
            node_id_contiguous_4_contiguous = new CharNode(CharClass.FromUndelimitedCharClassText("t"), "contiguous");
            node_id_contiguous_5_contiguous = new CharNode(CharClass.FromUndelimitedCharClassText("i"), "contiguous");
            node_id_contiguous_6_contiguous = new CharNode(CharClass.FromUndelimitedCharClassText("g"), "contiguous");
            node_id_contiguous_7_contiguous = new CharNode(CharClass.FromUndelimitedCharClassText("u"), "contiguous");
            node_id_contiguous_8_contiguous = new CharNode(CharClass.FromUndelimitedCharClassText("o"), "contiguous");
            node_id_contiguous_9_contiguous = new CharNode(CharClass.FromUndelimitedCharClassText("u"), "contiguous");
            node_id_contiguous_10_contiguous = new CharNode(CharClass.FromUndelimitedCharClassText("s"), "contiguous");
            node_id_contiguous_11_end = new EndNode();
            def_7_id_contiguous.Nodes.Add(node_id_contiguous_0_start);
            def_7_id_contiguous.Nodes.Add(node_id_contiguous_1_contiguous);
            def_7_id_contiguous.Nodes.Add(node_id_contiguous_2_contiguous);
            def_7_id_contiguous.Nodes.Add(node_id_contiguous_3_contiguous);
            def_7_id_contiguous.Nodes.Add(node_id_contiguous_4_contiguous);
            def_7_id_contiguous.Nodes.Add(node_id_contiguous_5_contiguous);
            def_7_id_contiguous.Nodes.Add(node_id_contiguous_6_contiguous);
            def_7_id_contiguous.Nodes.Add(node_id_contiguous_7_contiguous);
            def_7_id_contiguous.Nodes.Add(node_id_contiguous_8_contiguous);
            def_7_id_contiguous.Nodes.Add(node_id_contiguous_9_contiguous);
            def_7_id_contiguous.Nodes.Add(node_id_contiguous_10_contiguous);
            def_7_id_contiguous.Nodes.Add(node_id_contiguous_11_end);
            def_7_id_contiguous.start = node_id_contiguous_0_start;
            def_7_id_contiguous.end = node_id_contiguous_11_end;
            node_id_contiguous_0_start.NextNodes.Add(node_id_contiguous_1_contiguous);
            node_id_contiguous_1_contiguous.NextNodes.Add(node_id_contiguous_2_contiguous);
            node_id_contiguous_2_contiguous.NextNodes.Add(node_id_contiguous_3_contiguous);
            node_id_contiguous_3_contiguous.NextNodes.Add(node_id_contiguous_4_contiguous);
            node_id_contiguous_4_contiguous.NextNodes.Add(node_id_contiguous_5_contiguous);
            node_id_contiguous_5_contiguous.NextNodes.Add(node_id_contiguous_6_contiguous);
            node_id_contiguous_6_contiguous.NextNodes.Add(node_id_contiguous_7_contiguous);
            node_id_contiguous_7_contiguous.NextNodes.Add(node_id_contiguous_8_contiguous);
            node_id_contiguous_8_contiguous.NextNodes.Add(node_id_contiguous_9_contiguous);
            node_id_contiguous_9_contiguous.NextNodes.Add(node_id_contiguous_10_contiguous);
            node_id_contiguous_10_contiguous.NextNodes.Add(node_id_contiguous_11_end);

            def_8_expr.IgnoreCase = false;
            def_8_expr.IgnoreWhitespace = true;
            def_8_expr.Contiguous = false;
            node_expr_0_start = new StartNode();
            node_expr_1_subexpr = new DefRefNode(def_10_subexpr, "subexpr");
            node_expr_2_orexpr = new DefRefNode(def_9_orexpr, "orexpr");
            node_expr_3_comment = new DefRefNode(def_17_comment, "comment");
            node_expr_4_end = new EndNode();
            def_8_expr.Nodes.Add(node_expr_0_start);
            def_8_expr.Nodes.Add(node_expr_1_subexpr);
            def_8_expr.Nodes.Add(node_expr_2_orexpr);
            def_8_expr.Nodes.Add(node_expr_3_comment);
            def_8_expr.Nodes.Add(node_expr_4_end);
            def_8_expr.start = node_expr_0_start;
            def_8_expr.end = node_expr_4_end;
            node_expr_0_start.NextNodes.Add(node_expr_1_subexpr);
            node_expr_0_start.NextNodes.Add(node_expr_2_orexpr);
            node_expr_0_start.NextNodes.Add(node_expr_3_comment);
            node_expr_1_subexpr.NextNodes.Add(node_expr_1_subexpr);
            node_expr_1_subexpr.NextNodes.Add(node_expr_2_orexpr);
            node_expr_1_subexpr.NextNodes.Add(node_expr_3_comment);
            node_expr_1_subexpr.NextNodes.Add(node_expr_4_end);
            node_expr_2_orexpr.NextNodes.Add(node_expr_1_subexpr);
            node_expr_2_orexpr.NextNodes.Add(node_expr_2_orexpr);
            node_expr_2_orexpr.NextNodes.Add(node_expr_3_comment);
            node_expr_2_orexpr.NextNodes.Add(node_expr_4_end);
            node_expr_3_comment.NextNodes.Add(node_expr_1_subexpr);
            node_expr_3_comment.NextNodes.Add(node_expr_2_orexpr);
            node_expr_3_comment.NextNodes.Add(node_expr_3_comment);
            node_expr_3_comment.NextNodes.Add(node_expr_4_end);

            def_9_orexpr.IgnoreCase = false;
            def_9_orexpr.IgnoreWhitespace = true;
            def_9_orexpr.Contiguous = false;
            node_orexpr_0_start = new StartNode();
            node_orexpr_1__0028_ = new CharNode(CharClass.FromUndelimitedCharClassText("("), "(");
            node_orexpr_2_expr = new DefRefNode(def_8_expr, "expr");
            node_orexpr_3__007C_ = new CharNode(CharClass.FromUndelimitedCharClassText("|"), "|");
            node_orexpr_4_expr = new DefRefNode(def_8_expr, "expr");
            node_orexpr_5__0029_ = new CharNode(CharClass.FromUndelimitedCharClassText(")"), ")");
            node_orexpr_6_modifier = new DefRefNode(def_11_modifier, "modifier");
            node_orexpr_7_end = new EndNode();
            def_9_orexpr.Nodes.Add(node_orexpr_0_start);
            def_9_orexpr.Nodes.Add(node_orexpr_1__0028_);
            def_9_orexpr.Nodes.Add(node_orexpr_2_expr);
            def_9_orexpr.Nodes.Add(node_orexpr_3__007C_);
            def_9_orexpr.Nodes.Add(node_orexpr_4_expr);
            def_9_orexpr.Nodes.Add(node_orexpr_5__0029_);
            def_9_orexpr.Nodes.Add(node_orexpr_6_modifier);
            def_9_orexpr.Nodes.Add(node_orexpr_7_end);
            def_9_orexpr.start = node_orexpr_0_start;
            def_9_orexpr.end = node_orexpr_7_end;
            node_orexpr_0_start.NextNodes.Add(node_orexpr_1__0028_);
            node_orexpr_1__0028_.NextNodes.Add(node_orexpr_2_expr);
            node_orexpr_2_expr.NextNodes.Add(node_orexpr_3__007C_);
            node_orexpr_2_expr.NextNodes.Add(node_orexpr_5__0029_);
            node_orexpr_3__007C_.NextNodes.Add(node_orexpr_4_expr);
            node_orexpr_4_expr.NextNodes.Add(node_orexpr_3__007C_);
            node_orexpr_4_expr.NextNodes.Add(node_orexpr_5__0029_);
            node_orexpr_5__0029_.NextNodes.Add(node_orexpr_6_modifier);
            node_orexpr_5__0029_.NextNodes.Add(node_orexpr_7_end);
            node_orexpr_6_modifier.NextNodes.Add(node_orexpr_7_end);

            def_10_subexpr.IgnoreCase = false;
            def_10_subexpr.IgnoreWhitespace = true;
            def_10_subexpr.Contiguous = false;
            node_subexpr_0_start = new StartNode();
            node_subexpr_1_identifier = new DefRefNode(def_13_identifier, "identifier");
            node_subexpr_2_literal = new DefRefNode(def_14_literal, "literal");
            node_subexpr_3_charclass = new DefRefNode(def_15_charclass, "charclass");
            node_subexpr_4_modifier = new DefRefNode(def_11_modifier, "modifier");
            node_subexpr_5__003A_ = new CharNode(CharClass.FromUndelimitedCharClassText(":"), ":");
            node_subexpr_6_tag = new DefRefNode(def_13_identifier, "tag");
            node_subexpr_7_end = new EndNode();
            def_10_subexpr.Nodes.Add(node_subexpr_0_start);
            def_10_subexpr.Nodes.Add(node_subexpr_1_identifier);
            def_10_subexpr.Nodes.Add(node_subexpr_2_literal);
            def_10_subexpr.Nodes.Add(node_subexpr_3_charclass);
            def_10_subexpr.Nodes.Add(node_subexpr_4_modifier);
            def_10_subexpr.Nodes.Add(node_subexpr_5__003A_);
            def_10_subexpr.Nodes.Add(node_subexpr_6_tag);
            def_10_subexpr.Nodes.Add(node_subexpr_7_end);
            def_10_subexpr.start = node_subexpr_0_start;
            def_10_subexpr.end = node_subexpr_7_end;
            node_subexpr_0_start.NextNodes.Add(node_subexpr_1_identifier);
            node_subexpr_0_start.NextNodes.Add(node_subexpr_2_literal);
            node_subexpr_0_start.NextNodes.Add(node_subexpr_3_charclass);
            node_subexpr_1_identifier.NextNodes.Add(node_subexpr_4_modifier);
            node_subexpr_1_identifier.NextNodes.Add(node_subexpr_5__003A_);
            node_subexpr_1_identifier.NextNodes.Add(node_subexpr_7_end);
            node_subexpr_2_literal.NextNodes.Add(node_subexpr_4_modifier);
            node_subexpr_2_literal.NextNodes.Add(node_subexpr_5__003A_);
            node_subexpr_2_literal.NextNodes.Add(node_subexpr_7_end);
            node_subexpr_3_charclass.NextNodes.Add(node_subexpr_4_modifier);
            node_subexpr_3_charclass.NextNodes.Add(node_subexpr_5__003A_);
            node_subexpr_3_charclass.NextNodes.Add(node_subexpr_7_end);
            node_subexpr_4_modifier.NextNodes.Add(node_subexpr_5__003A_);
            node_subexpr_4_modifier.NextNodes.Add(node_subexpr_7_end);
            node_subexpr_5__003A_.NextNodes.Add(node_subexpr_6_tag);
            node_subexpr_6_tag.NextNodes.Add(node_subexpr_7_end);

            def_11_modifier.IgnoreCase = false;
            def_11_modifier.IgnoreWhitespace = true;
            def_11_modifier.Contiguous = false;
            node_modifier_0_start = new StartNode();
            node_modifier_1__002A__002B__003F_ = new CharNode(CharClass.FromUndelimitedCharClassText("*+?"), "*+?");
            node_modifier_2_end = new EndNode();
            def_11_modifier.Nodes.Add(node_modifier_0_start);
            def_11_modifier.Nodes.Add(node_modifier_1__002A__002B__003F_);
            def_11_modifier.Nodes.Add(node_modifier_2_end);
            def_11_modifier.start = node_modifier_0_start;
            def_11_modifier.end = node_modifier_2_end;
            node_modifier_0_start.NextNodes.Add(node_modifier_1__002A__002B__003F_);
            node_modifier_1__002A__002B__003F_.NextNodes.Add(node_modifier_2_end);

            def_12_number.IgnoreCase = false;
            def_12_number.IgnoreWhitespace = false;
            def_12_number.Contiguous = true;
            node_number_0_start = new StartNode();
            node_number_1__005C_d = new CharNode(CharClass.FromUndelimitedCharClassText("\\d"), "\\d");
            node_number_2_end = new EndNode();
            def_12_number.Nodes.Add(node_number_0_start);
            def_12_number.Nodes.Add(node_number_1__005C_d);
            def_12_number.Nodes.Add(node_number_2_end);
            def_12_number.start = node_number_0_start;
            def_12_number.end = node_number_2_end;
            node_number_0_start.NextNodes.Add(node_number_1__005C_d);
            node_number_1__005C_d.NextNodes.Add(node_number_1__005C_d);
            node_number_1__005C_d.NextNodes.Add(node_number_2_end);

            def_13_identifier.IgnoreCase = false;
            def_13_identifier.IgnoreWhitespace = false;
            def_13_identifier.Contiguous = true;
            node_identifier_0_start = new StartNode();
            node_identifier_1__005C_l_002D__ = new CharNode(CharClass.FromUndelimitedCharClassText("\\l-_"), "\\l-_");
            node_identifier_2__005C_l_005C_d_002D__ = new CharNode(CharClass.FromUndelimitedCharClassText("\\l\\d-_"), "\\l\\d-_");
            node_identifier_3_end = new EndNode();
            def_13_identifier.Nodes.Add(node_identifier_0_start);
            def_13_identifier.Nodes.Add(node_identifier_1__005C_l_002D__);
            def_13_identifier.Nodes.Add(node_identifier_2__005C_l_005C_d_002D__);
            def_13_identifier.Nodes.Add(node_identifier_3_end);
            def_13_identifier.start = node_identifier_0_start;
            def_13_identifier.end = node_identifier_3_end;
            node_identifier_0_start.NextNodes.Add(node_identifier_1__005C_l_002D__);
            node_identifier_1__005C_l_002D__.NextNodes.Add(node_identifier_2__005C_l_005C_d_002D__);
            node_identifier_1__005C_l_002D__.NextNodes.Add(node_identifier_3_end);
            node_identifier_2__005C_l_005C_d_002D__.NextNodes.Add(node_identifier_2__005C_l_005C_d_002D__);
            node_identifier_2__005C_l_005C_d_002D__.NextNodes.Add(node_identifier_3_end);

            def_14_literal.IgnoreCase = false;
            def_14_literal.IgnoreWhitespace = false;
            def_14_literal.Contiguous = false;
            node_literal_0_start = new StartNode();
            node_literal_1__0027_ = new CharNode(CharClass.FromUndelimitedCharClassText("'"), "'");
            node_literal_2__005E__005C__005C__0027_ = new CharNode(CharClass.FromUndelimitedCharClassText("^\\\\'"), "^\\\\'");
            node_literal_3__005C_ = new CharNode(CharClass.FromUndelimitedCharClassText("\\\\"), "\\");
            node_literal_4_rnt_005C__005C__0027_ = new CharNode(CharClass.FromUndelimitedCharClassText("rnt\\\\'"), "rnt\\\\'");
            node_literal_5_unicodechar = new DefRefNode(def_16_unicodechar, "unicodechar");
            node_literal_6__0027_ = new CharNode(CharClass.FromUndelimitedCharClassText("'"), "'");
            node_literal_7_end = new EndNode();
            def_14_literal.Nodes.Add(node_literal_0_start);
            def_14_literal.Nodes.Add(node_literal_1__0027_);
            def_14_literal.Nodes.Add(node_literal_2__005E__005C__005C__0027_);
            def_14_literal.Nodes.Add(node_literal_3__005C_);
            def_14_literal.Nodes.Add(node_literal_4_rnt_005C__005C__0027_);
            def_14_literal.Nodes.Add(node_literal_5_unicodechar);
            def_14_literal.Nodes.Add(node_literal_6__0027_);
            def_14_literal.Nodes.Add(node_literal_7_end);
            def_14_literal.start = node_literal_0_start;
            def_14_literal.end = node_literal_7_end;
            node_literal_0_start.NextNodes.Add(node_literal_1__0027_);
            node_literal_1__0027_.NextNodes.Add(node_literal_2__005E__005C__005C__0027_);
            node_literal_1__0027_.NextNodes.Add(node_literal_3__005C_);
            node_literal_1__0027_.NextNodes.Add(node_literal_5_unicodechar);
            node_literal_2__005E__005C__005C__0027_.NextNodes.Add(node_literal_2__005E__005C__005C__0027_);
            node_literal_2__005E__005C__005C__0027_.NextNodes.Add(node_literal_3__005C_);
            node_literal_2__005E__005C__005C__0027_.NextNodes.Add(node_literal_5_unicodechar);
            node_literal_2__005E__005C__005C__0027_.NextNodes.Add(node_literal_6__0027_);
            node_literal_3__005C_.NextNodes.Add(node_literal_4_rnt_005C__005C__0027_);
            node_literal_4_rnt_005C__005C__0027_.NextNodes.Add(node_literal_2__005E__005C__005C__0027_);
            node_literal_4_rnt_005C__005C__0027_.NextNodes.Add(node_literal_3__005C_);
            node_literal_4_rnt_005C__005C__0027_.NextNodes.Add(node_literal_5_unicodechar);
            node_literal_4_rnt_005C__005C__0027_.NextNodes.Add(node_literal_6__0027_);
            node_literal_5_unicodechar.NextNodes.Add(node_literal_2__005E__005C__005C__0027_);
            node_literal_5_unicodechar.NextNodes.Add(node_literal_3__005C_);
            node_literal_5_unicodechar.NextNodes.Add(node_literal_5_unicodechar);
            node_literal_5_unicodechar.NextNodes.Add(node_literal_6__0027_);
            node_literal_6__0027_.NextNodes.Add(node_literal_7_end);

            def_15_charclass.IgnoreCase = false;
            def_15_charclass.IgnoreWhitespace = false;
            def_15_charclass.Contiguous = false;
            node_charclass_0_start = new StartNode();
            node_charclass_1__005B_ = new CharNode(CharClass.FromUndelimitedCharClassText("\\["), "[");
            node_charclass_2__005E__005C__005C__005C__005B__005C__005D_ = new CharNode(CharClass.FromUndelimitedCharClassText("^\\\\\\[\\]"), "^\\\\\\[\\]");
            node_charclass_3__005C_ = new CharNode(CharClass.FromUndelimitedCharClassText("\\\\"), "\\");
            node_charclass_4_wldsrnt_005C__005C__005C__005B__005C__005D_ = new CharNode(CharClass.FromUndelimitedCharClassText("wldsrnt\\\\\\[\\]"), "wldsrnt\\\\\\[\\]");
            node_charclass_5_unicodechar = new DefRefNode(def_16_unicodechar, "unicodechar");
            node_charclass_6__005D_ = new CharNode(CharClass.FromUndelimitedCharClassText("\\]"), "]");
            node_charclass_7_end = new EndNode();
            def_15_charclass.Nodes.Add(node_charclass_0_start);
            def_15_charclass.Nodes.Add(node_charclass_1__005B_);
            def_15_charclass.Nodes.Add(node_charclass_2__005E__005C__005C__005C__005B__005C__005D_);
            def_15_charclass.Nodes.Add(node_charclass_3__005C_);
            def_15_charclass.Nodes.Add(node_charclass_4_wldsrnt_005C__005C__005C__005B__005C__005D_);
            def_15_charclass.Nodes.Add(node_charclass_5_unicodechar);
            def_15_charclass.Nodes.Add(node_charclass_6__005D_);
            def_15_charclass.Nodes.Add(node_charclass_7_end);
            def_15_charclass.start = node_charclass_0_start;
            def_15_charclass.end = node_charclass_7_end;
            node_charclass_0_start.NextNodes.Add(node_charclass_1__005B_);
            node_charclass_1__005B_.NextNodes.Add(node_charclass_2__005E__005C__005C__005C__005B__005C__005D_);
            node_charclass_1__005B_.NextNodes.Add(node_charclass_3__005C_);
            node_charclass_1__005B_.NextNodes.Add(node_charclass_5_unicodechar);
            node_charclass_2__005E__005C__005C__005C__005B__005C__005D_.NextNodes.Add(node_charclass_2__005E__005C__005C__005C__005B__005C__005D_);
            node_charclass_2__005E__005C__005C__005C__005B__005C__005D_.NextNodes.Add(node_charclass_3__005C_);
            node_charclass_2__005E__005C__005C__005C__005B__005C__005D_.NextNodes.Add(node_charclass_5_unicodechar);
            node_charclass_2__005E__005C__005C__005C__005B__005C__005D_.NextNodes.Add(node_charclass_6__005D_);
            node_charclass_3__005C_.NextNodes.Add(node_charclass_4_wldsrnt_005C__005C__005C__005B__005C__005D_);
            node_charclass_4_wldsrnt_005C__005C__005C__005B__005C__005D_.NextNodes.Add(node_charclass_2__005E__005C__005C__005C__005B__005C__005D_);
            node_charclass_4_wldsrnt_005C__005C__005C__005B__005C__005D_.NextNodes.Add(node_charclass_3__005C_);
            node_charclass_4_wldsrnt_005C__005C__005C__005B__005C__005D_.NextNodes.Add(node_charclass_5_unicodechar);
            node_charclass_4_wldsrnt_005C__005C__005C__005B__005C__005D_.NextNodes.Add(node_charclass_6__005D_);
            node_charclass_5_unicodechar.NextNodes.Add(node_charclass_2__005E__005C__005C__005C__005B__005C__005D_);
            node_charclass_5_unicodechar.NextNodes.Add(node_charclass_3__005C_);
            node_charclass_5_unicodechar.NextNodes.Add(node_charclass_5_unicodechar);
            node_charclass_5_unicodechar.NextNodes.Add(node_charclass_6__005D_);
            node_charclass_6__005D_.NextNodes.Add(node_charclass_7_end);

            def_16_unicodechar.IgnoreCase = true;
            def_16_unicodechar.IgnoreWhitespace = false;
            def_16_unicodechar.Contiguous = false;
            node_unicodechar_0_start = new StartNode();
            node_unicodechar_1__005C_x = new CharNode(CharClass.FromUndelimitedCharClassText("\\\\"), "\\x");
            node_unicodechar_2__005C_x = new CharNode(CharClass.FromUndelimitedCharClassText("x"), "\\x");
            node_unicodechar_3__005C_dabcdef = new CharNode(CharClass.FromUndelimitedCharClassText("\\dabcdef"), "\\dabcdef");
            node_unicodechar_4__005C_dabcdef = new CharNode(CharClass.FromUndelimitedCharClassText("\\dabcdef"), "\\dabcdef");
            node_unicodechar_5__005C_dabcdef = new CharNode(CharClass.FromUndelimitedCharClassText("\\dabcdef"), "\\dabcdef");
            node_unicodechar_6__005C_dabcdef = new CharNode(CharClass.FromUndelimitedCharClassText("\\dabcdef"), "\\dabcdef");
            node_unicodechar_7_end = new EndNode();
            def_16_unicodechar.Nodes.Add(node_unicodechar_0_start);
            def_16_unicodechar.Nodes.Add(node_unicodechar_1__005C_x);
            def_16_unicodechar.Nodes.Add(node_unicodechar_2__005C_x);
            def_16_unicodechar.Nodes.Add(node_unicodechar_3__005C_dabcdef);
            def_16_unicodechar.Nodes.Add(node_unicodechar_4__005C_dabcdef);
            def_16_unicodechar.Nodes.Add(node_unicodechar_5__005C_dabcdef);
            def_16_unicodechar.Nodes.Add(node_unicodechar_6__005C_dabcdef);
            def_16_unicodechar.Nodes.Add(node_unicodechar_7_end);
            def_16_unicodechar.start = node_unicodechar_0_start;
            def_16_unicodechar.end = node_unicodechar_7_end;
            node_unicodechar_0_start.NextNodes.Add(node_unicodechar_1__005C_x);
            node_unicodechar_1__005C_x.NextNodes.Add(node_unicodechar_2__005C_x);
            node_unicodechar_2__005C_x.NextNodes.Add(node_unicodechar_3__005C_dabcdef);
            node_unicodechar_3__005C_dabcdef.NextNodes.Add(node_unicodechar_4__005C_dabcdef);
            node_unicodechar_4__005C_dabcdef.NextNodes.Add(node_unicodechar_5__005C_dabcdef);
            node_unicodechar_5__005C_dabcdef.NextNodes.Add(node_unicodechar_6__005C_dabcdef);
            node_unicodechar_6__005C_dabcdef.NextNodes.Add(node_unicodechar_7_end);

            def_17_comment.IgnoreCase = false;
            def_17_comment.IgnoreWhitespace = false;
            def_17_comment.Contiguous = false;
            node_comment_0_start = new StartNode();
            node_comment_1__002F__002A_ = new CharNode(CharClass.FromUndelimitedCharClassText("/"), "/*");
            node_comment_2__002F__002A_ = new CharNode(CharClass.FromUndelimitedCharClassText("*"), "/*");
            node_comment_3__005E__002A_ = new CharNode(CharClass.FromUndelimitedCharClassText("^*"), "^*");
            node_comment_4__002A_ = new CharNode(CharClass.FromUndelimitedCharClassText("*"), "*");
            node_comment_5__005E__002A__002F_ = new CharNode(CharClass.FromUndelimitedCharClassText("^*/"), "^*/");
            node_comment_6__002A_ = new CharNode(CharClass.FromUndelimitedCharClassText("*"), "*");
            node_comment_7__002F_ = new CharNode(CharClass.FromUndelimitedCharClassText("/"), "/");
            node_comment_8__002F__002F_ = new CharNode(CharClass.FromUndelimitedCharClassText("/"), "//");
            node_comment_9__002F__002F_ = new CharNode(CharClass.FromUndelimitedCharClassText("/"), "//");
            node_comment_10__005E__005C_r_005C_n = new CharNode(CharClass.FromUndelimitedCharClassText("^\\r\\n"), "^\\r\\n");
            node_comment_11__005C_r_005C_n = new CharNode(CharClass.FromUndelimitedCharClassText("\\r\\n"), "\\r\\n");
            node_comment_12_end = new EndNode();
            def_17_comment.Nodes.Add(node_comment_0_start);
            def_17_comment.Nodes.Add(node_comment_1__002F__002A_);
            def_17_comment.Nodes.Add(node_comment_2__002F__002A_);
            def_17_comment.Nodes.Add(node_comment_3__005E__002A_);
            def_17_comment.Nodes.Add(node_comment_4__002A_);
            def_17_comment.Nodes.Add(node_comment_5__005E__002A__002F_);
            def_17_comment.Nodes.Add(node_comment_6__002A_);
            def_17_comment.Nodes.Add(node_comment_7__002F_);
            def_17_comment.Nodes.Add(node_comment_8__002F__002F_);
            def_17_comment.Nodes.Add(node_comment_9__002F__002F_);
            def_17_comment.Nodes.Add(node_comment_10__005E__005C_r_005C_n);
            def_17_comment.Nodes.Add(node_comment_11__005C_r_005C_n);
            def_17_comment.Nodes.Add(node_comment_12_end);
            def_17_comment.start = node_comment_0_start;
            def_17_comment.end = node_comment_12_end;
            node_comment_0_start.NextNodes.Add(node_comment_1__002F__002A_);
            node_comment_0_start.NextNodes.Add(node_comment_8__002F__002F_);
            node_comment_1__002F__002A_.NextNodes.Add(node_comment_2__002F__002A_);
            node_comment_2__002F__002A_.NextNodes.Add(node_comment_3__005E__002A_);
            node_comment_2__002F__002A_.NextNodes.Add(node_comment_4__002A_);
            node_comment_2__002F__002A_.NextNodes.Add(node_comment_6__002A_);
            node_comment_3__005E__002A_.NextNodes.Add(node_comment_3__005E__002A_);
            node_comment_3__005E__002A_.NextNodes.Add(node_comment_4__002A_);
            node_comment_3__005E__002A_.NextNodes.Add(node_comment_6__002A_);
            node_comment_4__002A_.NextNodes.Add(node_comment_4__002A_);
            node_comment_4__002A_.NextNodes.Add(node_comment_5__005E__002A__002F_);
            node_comment_5__005E__002A__002F_.NextNodes.Add(node_comment_3__005E__002A_);
            node_comment_5__005E__002A__002F_.NextNodes.Add(node_comment_4__002A_);
            node_comment_5__005E__002A__002F_.NextNodes.Add(node_comment_6__002A_);
            node_comment_6__002A_.NextNodes.Add(node_comment_6__002A_);
            node_comment_6__002A_.NextNodes.Add(node_comment_7__002F_);
            node_comment_7__002F_.NextNodes.Add(node_comment_12_end);
            node_comment_8__002F__002F_.NextNodes.Add(node_comment_9__002F__002F_);
            node_comment_9__002F__002F_.NextNodes.Add(node_comment_10__005E__005C_r_005C_n);
            node_comment_9__002F__002F_.NextNodes.Add(node_comment_11__005C_r_005C_n);
            node_comment_10__005E__005C_r_005C_n.NextNodes.Add(node_comment_10__005E__005C_r_005C_n);
            node_comment_10__005E__005C_r_005C_n.NextNodes.Add(node_comment_11__005C_r_005C_n);
            node_comment_11__005C_r_005C_n.NextNodes.Add(node_comment_11__005C_r_005C_n);
            node_comment_11__005C_r_005C_n.NextNodes.Add(node_comment_12_end);

        }
    }
}

